USER_NOT_FOUND = "Requested User Not Found"
INVALID_CREDENTIALS = "Username or Password Invalid"
RECORD_NOT_FOUND = "Record(s) not found in database"
INVALID_REQUEST_BODY = "Invalid Parameters"
USER_ALREADY_EXISTS = "Username Already Exists"
